
builds:
- main: ./cmd/s3backup
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^bin:'
    - '^docs:'
    - '^libexec:'
    - '^scripts:'
    - '^share:'
    - '^test:'
    - '^tmp:'
    - '^vendor:'
