version: '3.7'

services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4563-4599:4563-4599'
      - '8055:8080'
    environment:
      - SERVICES=s3
      - DEBUG=1
      - START_WEB=0
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    # volumes:
    #   - './.localstack:/tmp/localstack'
  test:
    build:
      dockerfile: ./tests.dockerfile
      context: .
    depends_on:
      - localstack
    entrypoint: ''
    environment:
      - PATH="${PWD}/bin:${PATH}"
    volumes:
      - '.:/src'
      - './scripts:/scripts'
